/**
 * 全局技能库短描述（中文）。
 * Key = 技能 id（不翻译）；value = 列表/预览用的一句中文说明。
 * 缺省时回退接口返回的英文 description。
 */
export const SKILL_DESCRIPTIONS_ZH: Record<string, string> = {
  airtable: '通过 curl 调用 Airtable REST：记录增删改查与筛选。',
  'architecture-diagram': '生成深色主题的架构 / 云图 / 基础设施 SVG 图。',
  arxiv: '按关键词、作者、分类或 ID 检索 arXiv 论文。',
  'ascii-art': 'ASCII 艺术：pyfiglet、cowsay、boxes、图片转 ASCII。',
  'ascii-video': '将视频 / 音频转为彩色 ASCII 的 MP4 或 GIF。',
  'audiocraft-audio-generation': 'AudioCraft：文生音乐（MusicGen）与文生音效（AudioGen）。',
  'baoyu-article-illustrator': '按类型 × 风格 × 色板生成文章配图，保持视觉一致。',
  'baoyu-comic': '知识漫画：科普、传记、教程类分镜漫画。',
  'baoyu-infographic': '信息图：多种布局与风格组合的可视化。',
  blogwatcher: '用 blogwatcher-cli 监控博客与 RSS/Atom 订阅。',
  'claude-code': '将编码任务委派给 Claude Code CLI（功能与 PR）。',
  'claude-design': '制作一次性 HTML 设计稿（落地页、演示、原型）。',
  'codebase-inspection': '用 pygount 统计代码库行数、语言占比等。',
  codex: '将编码任务委派给 OpenAI Codex CLI。',
  comfyui: '用 ComfyUI 生成图像、视频与音频，并管理节点。',
  'debugging-hermes-tui-commands': '调试 Hermes TUI 斜杠命令：Python、网关与 Ink UI。',
  'design-md': '编写 / 校验 / 导出 Google DESIGN.md 设计令牌规范。',
  dogfood: '对 Web 应用做探索性 QA：找缺陷并整理证据报告。',
  dspy: 'DSPy：声明式 LM 程序、提示优化与 RAG。',
  'evaluating-llms-harness': '用 lm-eval-harness 跑 LLM 基准（MMLU、GSM8K 等）。',
  excalidraw: '生成手绘风 Excalidraw 图（架构、流程、时序）。',
  'gif-search': '通过 Tenor 用 curl + jq 搜索并下载 GIF。',
  'github-auth': '配置 GitHub 认证：HTTPS token、SSH、gh 登录。',
  'github-code-review': '审查 PR：查看 diff，并通过 gh 或 REST 发表评论。',
  'github-issues': '用 gh 或 REST 创建、分流、打标签与指派 Issue。',
  'github-pr-workflow': 'GitHub PR 全流程：分支、提交、打开、CI、合并。',
  'github-repo-management': '克隆 / 创建 / fork 仓库，管理远端与 release。',
  godmode: 'LLM jailbreak 相关手法（研究 / 红队场景）。',
  'google-workspace': '通过 gws 或 Python 操作 Gmail、日历、云盘、文档、表格。',
  heartmula: 'HeartMuLa：根据歌词与标签生成类 Suno 歌曲。',
  'hermes-agent': '配置、扩展或向 Hermes Agent 贡献能力。',
  'hermes-agent-skill-authoring': '编写仓内 SKILL.md：frontmatter、校验与结构规范。',
  'hermes-s6-container-supervision': '修改或调试 Hermes 容器内的 s6-overlay 监督树。',
  himalaya: 'Himalaya CLI：在终端收发 IMAP/SMTP 邮件。',
  'huggingface-hub': 'HuggingFace CLI：搜索 / 下载 / 上传模型与数据集。',
  humanizer: '去 AI 味，把文本改写成更自然的人声文风。',
  ideation: '用创意约束批量生成项目点子。',
  'jupyter-live-kernel': '通过实时 Jupyter 内核做迭代式 Python 探索。',
  'kanban-codex-lane': 'Kanban worker 用 Codex CLI 做隔离实现通道时使用。',
  'kanban-orchestrator': '编排型 profile 拆解任务与防诱惑规则的操作手册。',
  'kanban-worker': 'Hermes Kanban worker 的陷阱、示例与边界情况。',
  linear: '通过 GraphQL + curl 管理 Linear 议题与项目。',
  'llama-cpp': 'llama.cpp 本地 GGUF 推理，并发现 HuggingFace 模型。',
  'llm-wiki': 'Karpathy 式 LLM Wiki：构建与查询互联 Markdown 知识库。',
  'manim-video': 'Manim CE 动画：类 3Blue1Brown 的数学 / 算法视频。',
  maps: '通过 OpenStreetMap/OSRM 做地理编码、POI、路线与时区。',
  'minecraft-modpack-server': '托管整合包 Minecraft 服（CurseForge、Modrinth）。',
  'nano-pdf': '用 nano-pdf CLI（自然语言）修改 PDF 文字与标题。',
  'native-mcp': 'MCP 客户端：连接服务器并注册工具（stdio/HTTP）。',
  'node-inspect-debugger': '用 --inspect 与 Chrome DevTools 协议调试 Node.js。',
  notion: 'Notion API / ntn CLI：页面、数据库、Markdown 与 Workers。',
  obliteratus: 'OBLITERATUS：消减 LLM 拒绝倾向（研究用途）。',
  obsidian: '在 Obsidian 库中读写、搜索、创建与编辑笔记。',
  'ocr-and-documents': '从 PDF / 扫描件抽取文本（pymupdf、marker-pdf）。',
  opencode: '将编码任务委派给 OpenCode CLI。',
  openhue: '用 OpenHue CLI 控制飞利浦 Hue 灯、场景与房间。',
  p5js: 'p5.js 草图：生成艺术、着色器、交互与 3D。',
  'pixel-art': '按时代色板绘制像素画（NES、Game Boy、PICO-8）。',
  plan: '计划模式：把 markdown 计划写入 .hermes/plans/，不直接执行。',
  'pokemon-player': '通过无头模拟器与 RAM 读取游玩宝可梦。',
  polymarket: '查询 Polymarket：市场、价格、订单簿与历史。',
  'popular-web-designs': '把 Stripe、Linear、Vercel 等真实设计系统写成 HTML/CSS。',
  powerpoint: '创建与编辑 .pptx 演示文稿、幻灯片、备注与模板。',
  pretext: '用 @chenglou/pretext 做无 DOM 依赖的创意浏览器演示。',
  'python-debugpy': '调试 Python：pdb REPL 与 debugpy 远程（DAP）。',
  'requesting-code-review': '提交前审查：安全扫描、质量门槛与自动修复。',
  'research-paper-writing': '撰写 NeurIPS/ICML/ICLR 等会议向机器学习论文。',
  'segment-anything-model': 'SAM：用点、框、掩码做零样本图像分割。',
  'serving-llms-vllm': 'vLLM 高吞吐量 LLM 服务，兼容 OpenAI API 与量化。',
  sketch: '快速 HTML 线框图：一次产出 2–3 个方案便于对比。',
  songsee: '音频频谱 / 特征（mel、chroma、MFCC）命令行分析。',
  'songwriting-and-ai-music': '歌曲创作技巧与 Suno 类 AI 音乐提示词。',
  spike: '抛实验证想法的短跑，避免过早正式开发。',
  spotify: 'Spotify：播放、搜索、队列与歌单 / 设备管理。',
  'subagent-driven-development': '用 delegate_task 子代理按计划执行（两阶段审查）。',
  'systematic-debugging': '四阶段根因调试：先理解问题再动手改。',
  'teams-meeting-pipeline': '用 Hermes CLI 运行 Teams 会议摘要流水线。',
  'test-driven-development': 'TDD：先失败测试 → 实现 → 重构。',
  'touchdesigner-mcp': '经 MCP 控制运行中的 TouchDesigner（创建算子等）。',
  'webhook-subscriptions': 'Webhook 订阅：事件驱动触发 Agent 运行。',
  'weights-and-biases': 'W&B：记录实验、扫参、模型注册与看板。',
  'writing-plans': '写可执行实现计划：小任务、路径与示例代码。',
  xurl: '用 xurl CLI 操作 X/Twitter：发帖、搜索、私信与媒体。',
  'youtube-content': '把 YouTube 字幕整理成摘要、帖子或博客。',
  yuanbao: '元宝群：@成员、查询群信息与成员。',
}

/** 列表展示用描述：中文环境优先映射，否则回退原文。技能名本身不翻译。 */
export function skillDisplayDescription(
  locale: string,
  skillName: string,
  fallback?: string | null,
): string {
  if (locale === 'zh') {
    const zh = SKILL_DESCRIPTIONS_ZH[skillName]
    if (zh) return zh
  }
  return (fallback ?? '').trim()
}
